/* eslint-disable no-shadow */
enum COLLISION_TAGS {
  MEGAMAN,
  BREAKABLE_FLOOR,
  CRUSHER_SENSOR,
  CRUSHER,
  FLOOR_BREAKER_DISABLED,
  BREAKABLE_FLOOR_TARGET,
  BULLET,
  LONG_FLOOR,
  BEE_BLADER,
  BEE_BLADER_SENSOR,
  BEE_BLADER_BOMB,
}

export default COLLISION_TAGS;
