/* eslint-disable no-shadow */
enum COLLISION_TAGS {
  MEGAMAN,
  BREAKABLE_FLOOR,
  CRUSHER_SENSOR,
  CRUSHER,
  FLOOR_BREAKER_DISABLED,
  BREAKABLE_FLOOR_TARGET,
  BULLET,
  LONG_FLOOR,
  BEE_BLADER,
  BEE_BLADER_SENSOR,
  BEE_BLADER_BOMB,
  GUN_VOLT,
  GUN_VOLT_SENSOR,
  GUN_VOLT_ENERGY_BALLS,
  GUN_VOLT_ROCKET,
  ROAD_ATTACKER,
  ROAD_ATTACKER_BULLET,
  BOMB_BEEN,
  BOMB_BEEN_BOMB,
  JAMMINGER,
  BALL_DE_VOUX,
  SPIKY,
}

export default COLLISION_TAGS;
