/* eslint-disable no-shadow */
enum PHYSICAL_COLLISION_TAGS {
  MEGAMAN_FEET,
  MEGAMAN_LEFT_SIDE,
  MEGAMAN_RIGHT_SIDE,
  FLOOR,
  LEFT_WALL,
  RIGHT_WALL,
  BEE_BLADER,
}

export default PHYSICAL_COLLISION_TAGS;
